version: '3'

silent: true

vars:
  TOOLCHAIN: +1.95.0 # Rust toolchain for building testing contracts.

tasks:

  build:
    desc: Build in debug mode
    cmds:
      - cmd: cargo {{.TOOLCHAIN}} build --workspace

  check-contracts:
    desc: Performs checks for all contracts
    cmds:
      - task: install-cosmwasm-check
      - cmd: ./devtools/check-contracts.sh

  clean:
    desc: Removes all compiled artifacts
    cmds:
      - task: clean
      - cmd: ./devtools/clean-contracts.sh

  fmt:
    desc: Runs code formatter
    cmds:
      - cmd: cargo {{.TOOLCHAIN}} fmt

  release:
    desc: Build in release mode
    cmds:
      - cmd: cargo {{.TOOLCHAIN}} build --release --workspace

  wasm:
    desc: Build in release mode
    cmds:
      - cmd: cargo {{.TOOLCHAIN}} build --release --lib --target wasm32-unknown-unknown --workspace

  update-schemas:
    desc: Updates schemas for all contracts
    cmds:
      - cmd: ./devtools/update-schemas.sh

  install-cosmwasm-check:
    desc: Installs cosmwasm-check tool (released version and currently developed version)
    cmds:
      - cmd: cargo {{.TOOLCHAIN}} install --path ../cosmwasm/packages/check --locked --force
